### ISSUE TITLE
Add formatting button for Underline

### ISSUE THREAD

**Issue by ASVc6** [Reocin/obsidian-markdown-formatting-assistant-plugin#12]
**Is your feature request related to a problem? Please describe.**
- No

**Describe the solution you'd like**
- Add a formatting button for Underline. When hit, the selected text will be surrounded by `<u></u>`. Typora has that format command in the menu, so I guess it's quite commonly used.

**Describe alternatives you've considered**
- A setting UI where user can add any tag and its shortcut. This covers cases where tags that frequently used by a few users might not be commonly used by others.

**Additional context**
- None

**Comment by Reocin** [comment]
Hey @ASVc6 

I added a Underline button in the Text Edit section and as it actually is a HTML feature and not Markdown in the HTML section. Just update the plugin in the settings and restart obsidian. You will find some other new stuff ;-)

**Comment by Reocin** [comment]
Ah i forgot to answer to your second point. Actually i already have planned such a feature, but this plugin is really new and i need the feedback of the users to improve it. That's the reason why it is not implemented yet ;-).

**Comment by Benature** [comment]
I want to have a shorcut like `cmd+U` for the underline too. Really looking forward to this feature!!!
