### ISSUE TITLE
<p>

### ISSUE THREAD

**Issue by zhl111** [Reocin/obsidian-markdown-formatting-assistant-plugin#14]
**Describe the bug**

**To Reproduce**
2. Click on `<p>`

![image](https://user-images.githubusercontent.com/29135984/113165334-6f885780-9274-11eb-8cac-801cc9b1eb57.png)

**Comment by Reocin** [comment]
Oh thanks the input parameter was shifted, will be fixed soon :-)

**Comment by Reocin** [comment]
@zhl111 Hey the bug is resolved. Just update the plugin to the new version and restart obsidian.
