### ISSUE TITLE
FR: Highlights

### ISSUE THREAD

**Issue by a-marionette** [Reocin/obsidian-markdown-formatting-assistant-plugin#16]
**Is your feature request related to a problem? Please describe.**
Currently, it does not seem possible to highlight items using the assistant.

**Describe the solution you'd like**
Would like the assistant to have a button to highlight based on a default set of colors.

**Comment by Reocin** [comment]
Hey thanks for your input. Do you already did that with some html snipes ? If yes, could you please show me some examples ? This would reduce the effort for me :-) 

Regards

**Comment by a-marionette** [comment]
Here is an example of a type of highlight in the form of a gradient underline. It would be pretty cool to be able to select a set of default colors for the highlight. Here is the snippet I extracted below the URL:

https://www.inverse.com/gaming/ff7-remake-intergrade-twist-huge-materia-yuffie

```
.tOr a, .AqC>h3 a, .AqC h2 a, .AqC h4 a, .AqC li a, .AqC p a, .rZx a {
    border-bottom: var(--linkBorderHeight) solid var(--slot3);
    border-bottom-width: var(--linkBorderHeight);
    border-image: linear-gradient(
70deg
,var(--slot3) 35%,var(--slot4) 70%,var(--slot5)) 1;
    border-left-width: 0;
    border-right-width: 0;
    border-top-width: 0;
    color: inherit;
```

**Comment by Reocin** [comment]
Hey, sorry for my late replay. I am busy at work. I just released a new Version with a highlight button :-) But no option to select a color. Probably one day. Buuut ;-) I imporved also the color-picker where you can add the option (via checkboxes) to add the style tag for you automatically as you insert a color. So just go there, select the options background-color and style=" ... " and you have your background in your color.

Like `<mark style="background-color: #ff0000">sdfsdf</mark>`

Is this ok for you ? 

Regards Daniel
