### ISSUE TITLE
Error parsing Mermaid diagram

### ISSUE THREAD

**Issue by AytoMaximo** [Reocin/obsidian-markdown-formatting-assistant-plugin#17]
**Describe the bug**
The plugin can't parse any of mermaid examples besides the simplest one from the [documentation](https://mermaid-js.github.io/mermaid/#/) or [Mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor/)

**To Reproduce**
1. Insert mermaid block
2. Copy any example from the links above and paste it in the mermaid block in Obsidian
3. Switch to preview mode

**Example block of code**
```
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

**The error message**
```
Error parsing Mermaid diagram!

Parse error on line 3:
...ph TD A\[Christmas\] \-->|Get&nbsp;mon
---------------------^
Expecting 'SPACE', 'GRAPH', 'DIR', 'subgraph', 'SQE', 'end', 'AMP', 'TAGEND', 'START_LINK', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DOWN', 'UP', 'DEFAULT', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'MINUS', 'BRKT', 'DOT', 'PCT', 'TAGSTART', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'TRAPEND'
```

**Expected behavior**
I'm expecting to see the same picture as in the examples or get some mermaid syntax and its features documentation of the plugin.

**Comment by Reocin** [comment]
@AytoMaximo  Hello and thanks for your response.

Actually i have no clue about this topic, because this was a pull request from the other user @AlexMikhalev. Do you know more about this ?

**Comment by AlexMikhalev** [comment]
The example above works for me, see code in [raw gist](https://gist.githubusercontent.com/AlexMikhalev/520295d0ba2801822874e6e023067d25/raw/cd12b590b104bbcddd622558caefd8737b6394ec/mermaid.md)

**Comment by Reocin** [comment]
@AlexMikhalev  Thanks for your help i just tested it in my obsidian, and it worked too (see image). Probably you have a copy and paste issue? I see in your error backslashes which could happen when copy with normal `ctrl-V ` try it with `ctrl-shift-v`.

Regards daniel


![image](https://user-images.githubusercontent.com/35258423/115692181-0a012580-a35f-11eb-985d-1dc7778d7c51.png)

**Comment by AlexMikhalev** [comment]
My guess GraphTD was on the same line as mermaid with ticks and was ignored.

**Comment by AytoMaximo** [comment]
I've paste the raw example from @AlexMikhalev , it's NOT working for me

![image](https://user-images.githubusercontent.com/14392087/115702395-8dc40d80-a371-11eb-9a42-84307295a5b6.png)
![image](https://user-images.githubusercontent.com/14392087/115702408-9288c180-a371-11eb-9d47-665f5e109c51.png)

**Comment by AlexMikhalev** [comment]
See previous comment, you are escaping brackets.

**Comment by Reocin** [comment]
@AytoMaximo you are welcome, have fun with obsidian :-)

That is a behaviour of Obsidian, with the normal copy and past it tries to convert the copied data to obsidian syntax. And as you don't want any parsing you have to use the ctrl+shift+V.
