### ISSUE TITLE
Add html list snippet

### ISSUE THREAD

**Issue by lucpaoli** [Reocin/obsidian-markdown-formatting-assistant-plugin#22]
i.e.
<ol type="a">
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>

To allow for easy alphabetical lists

**Comment by lucpaoli** [comment]
Customisable snippets (via commands) would be ideal - if this isn't available/planned to be available, I'd love for someone to point me in a possible direction

**Comment by lucpaoli** [comment]
As I said this, I found a plugin that did what i was looking for :)

**Comment by Reocin** [comment]
Ok, but hope you still use my plugin 🙃😉
