### ISSUE TITLE
$$x$$ and $x$ are switched wrong

### ISSUE THREAD

**Issue by Y0ngg4n** [Reocin/obsidian-markdown-formatting-assistant-plugin#23]
The button $$x$$ and $x$ do the exact opposite of each other.

**Comment by Reocin** [comment]
Oh Thanks! Will be changed in the next release!

**Comment by Y0ngg4n** [comment]
@Reocin Thank you for you fast answer :) I am excited for the next release ;)

**Comment by Reocin** [comment]
At the moment i'm really busy at work. So i don't know when this on will come. Try my best 😉

**Comment by Y0ngg4n** [comment]
@Reocin Alright :) Don´t get stressed by the Issues ;)

**Comment by Reocin** [comment]
As i said, this issue is closed with the new release. Just update to the new Version.

Regards Daniel
