### ISSUE TITLE
The layouts overlap

### ISSUE THREAD

**Issue by PaulHerrero** [Reocin/obsidian-markdown-formatting-assistant-plugin#25]
Hi, I have just updated to the latest version and found that the layouts overlap.

![Snipaste_2021-06-13_09-00-43](https://user-images.githubusercontent.com/56058332/121792357-51e94e00-cc26-11eb-9a14-84d10e701c3d.png)

**Comment by Reocin** [comment]
Hallo @PaulHerrero how did you manage it to get there ? I tried everything, but on my machine it just works, even if I switch the with opened sections. I have some further questions....

Is this problem still present after a restart ?
What kind of operating system do you have ? Windows/Mac/Linux
What is your Version of your Obsidian ?

regards Daniel

**Comment by PaulHerrero** [comment]
Thanks for the reply, I think I found the reason. The problem is not caused by the plugin but by third party css styles. I switched to the system default look and the problem was solved.

![Snipaste_2021-06-13_14-43-48](https://user-images.githubusercontent.com/56058332/121797942-f040d800-cc55-11eb-87f6-86f03fa76484.png)

**Comment by Reocin** [comment]
Oh, then the CSS messed up with some default layouts of obsidian. I don't have a lot CSS included. Thanks for your replay, it will help people with a similar issue. I will close the task. 

Regards reocin
