### ISSUE TITLE
Problem With Using Hot Keys 

### ISSUE THREAD

**Issue by Archie-2021** [Reocin/obsidian-markdown-formatting-assistant-plugin#26]
Hi,

I recently made a ahk script for mapping my direction keys to the center of keyboard and it works fine except when I want to use command function of your plugin (using direction keys directly works). I have no idea why such a thing for mapping key should make a issue for one program but not others. But I really appreciate if you fix it, it is going to become very useful for me.

Thanks you in advance

**Comment by Reocin** [comment]
@Archie-2021 Hey What keys do you use? I'm not sure if i can follow you.

So you have the normal direction keys, left right up and down and you mapped it for example to w,a,s,d ? Like in the lost games...

**Comment by Archie-2021** [comment]
Yeah kinda. I mapped it to capslock and i and k for going up and down, and j and l for left and right. It changes the capslock itself to double tapping. It worked so far fine in every other app including obsidian dropdown menues like quick switcher. I can send the whole code for you if you need to look. It's just a few lines.

**Comment by Reocin** [comment]
Hey the trigger command will be changed and works with a normal suggestion pane from obsidian. Then this bug should be also solved.

Pleas follow the Issue https://github.com/Reocin/obsidian-markdown-formatting-assistant-plugin/issues/54

**Comment by Reocin** [comment]
Hey guys, it is just a quick fix, but the plugin should work again. **Please make sure that you use an obsidian version 0.15.x and update the plugin to the version 0.4.0**

Read also read the README for the new replacement of the trigger command `\`. It works now with the hotkey `ALT+Q` (it is just a quick update of the README. I will go through on another day)
