### ISSUE TITLE
The highlighted is not Markdown is HTML

### ISSUE THREAD

**Issue by javiavid** [Reocin/obsidian-markdown-formatting-assistant-plugin#29]
**Describe the bug**
Is applying <mark> </ mark> instead of ====

**To Reproduce**
1. Go to 'markdown toolbar'
2. Click on 'highligth button'

**Desktop (please complete the following information):**
 - OS: [Win10 last update]
 - Obsidian Version [12.10]
 - Markdown plugin [0.3.2]

**Comment by Reocin** [comment]
Oh didn't know that this exists, that's way I used html. Perfect, I will change that in the next release.

Thanks!

**Comment by Reocin** [comment]
PS: This is now also fixed!
----

Hey guys, it is just a quick fix, but the plugin should work again. **Please make sure that you use an obsidian version 0.15.x and update the plugin to the version 0.4.0**

Read also read the README for the new replacement of the trigger command `\`. It works now with the hotkey `ALT+Q` (it is just a quick update of the README. I will go through on another day)
