### ISSUE TITLE
Trigger character/command language no longer working

### ISSUE THREAD

**Issue by 2chg** [Reocin/obsidian-markdown-formatting-assistant-plugin#41]
**Describe the bug**
I don't know if it's related with a recent update of Obsidian, but the trigger character/command language is no longer working.

**To Reproduce**
1. Open a new note (in edit mode)
2. Type `\co` (or any other command like `\h4` for Heading 4)
3. Now it should autocomplete to *Code Block*, but not completion or popup appears

**Expected behavior**
As described in the section [Command Language](https://github.com/Reocin/obsidian-markdown-formatting-assistant-plugin#command-language) a popup with possible command should appear and after selecting one the corresponding template should be inserted.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v0.13.14

**Additional context**
As far as I remember, I didn't install another plugin or changed a specific obsidian setting in the near past.
I also already disabled all other community plugins and restarted Obsidian, as well as changed the trigger character trying to *refresh* the plugin.

**Comment by Moggel12** [comment]
This is also a problem for Obsidian v0.13.23 on Arch Linux.

**Comment by drakeguan** [comment]
The same here (I'm quite new to Obsidian, and unfortunately, my 1st trial of this plugin doesn't see the autocomplete popup).

Some info:
- OS: macOS 11.6
- Obsidian Version: v0.13.14
- Theme: Minimal Theme
- Editor mode: Vim key bindings (enabled)
- external bluetooth keyboard (should not be an issue, but... who knows)

**Comment by KraXen72** [comment]
same here, since live preview rolled out, the command language doesen't work

**Comment by vawalker** [comment]
New to Obsidian; same issue where trigger command isn't doing anything in live-preview mode.
OS: Windows 10, Obsidian: v0.13.23

**Comment by lena-schwert** [comment]
Same here on Ubuntu 22.04 running Obsidian 0.14.6 with the AppImage, using the live preview.

**Comment by aannasw** [comment]
Just installed the plugin on Vault v0.14.15 on macOS Monterey 12.2.1 and seeing the same issue. Tried in source mode and in live preview, and as suggested above, also tried turning off all other plugins and using the default theme.

**Comment by Reocin** [comment]
Hey guys sorry for my late reaction. My time was/is consumed by my new job. The command feature will work again in the next release. (Also the hole plugin as it don't work anymore with the latest API changes) 

I have to mention it won't work same way as before. Please follow the other Issue: https://github.com/Reocin/obsidian-markdown-formatting-assistant-plugin/issues/54

**Comment by Reocin** [comment]
Hey guys, it is just a quick fix, but the plugin should work again. **Please make sure that you use an obsidian version 0.15.x and update the plugin to the version 0.4.0**

Read also read the README for the new replacement of the trigger command `\`. It works now with the hotkey `ALT+Q` (it is just a quick update of the README. I will go through on another day)
