### ISSUE TITLE
The plugin does not work

### ISSUE THREAD

**Issue by chumido98** [Reocin/obsidian-markdown-formatting-assistant-plugin#46]
**Describe the bug**
I typied trigger char but nothing happen. I already tried to change trigger char, reinstall plugin, reinstall obsidian but still not work.

**Screenshots**
![CleanShot 2022-03-16 at 09 15 37@2x](https://user-images.githubusercontent.com/61721378/158503290-f9a0b0d2-d679-4fff-8957-b6c7ae348ccf.jpg)

**Desktop:**
 - OS: MacOS Monterey 12.3
 - App: Obsidian v0.13.33
 - Plugin Version: 0.3.2

Please help me, thank you.

**Comment by gkavboy** [comment]
I approve this behavior. Trigger not work.

**Comment by RaduPrusan** [comment]
Trigger doesn't work.

**Comment by wealthychef1** [comment]
Agreed, trigger not working for me either.  But then again, I don't know how to use this tool to apply color to text.  A simple guide video would be helpful...

**Comment by Izzy1647** [comment]
Doesn't work here as well, MacOS Monterey 12.0.1

**Comment by dirkvandamme** [comment]
I experiene the same as described by [chumido98]

MacOS 12.4
Obsidian 0.15.6
Plugin : 0.3.2

**Comment by johnw721** [comment]
Can confirm that I am experiencing the same problem. 
The screenshot included shows how I been attempting to use the plugin. 
I turned off all other plugins, restarted the plugin, and also restarted obsidian. 

Windows 11 Home Edition
Obsidian v0.15.6
Obsidian-Markdown-Formatting-Assistant 0.3.2

**Comment by Reocin** [comment]
Hey Guys thanks for your replay, and sorry for my late response. My new job consumed all my time. I will fix this in the next release. And as the plugin don't work anymore with the new API i have to update the most of it anyway. 

Please follow the issue: https://github.com/Reocin/obsidian-markdown-formatting-assistant-plugin/issues/54

**Comment by Reocin** [comment]
Hey guys, it is just a quick fix, but the plugin should work again. **Please make sure that you use an obsidian version 0.15.x and update the plugin to the version 0.4.0**

Read also read the README for the new replacement of the trigger command `\`. It works now with the hotkey `ALT+Q` (it is just a quick update of the README. I will go through on another day)

**Comment by dirkvandamme** [comment]
Many thanks Reocin for the update!! it works fine. Very much appreciated!!
