### ISSUE TITLE
Markdown Formatting Assistent GUI display bug.  

### ISSUE THREAD

**Issue by wealthychef1** [Reocin/obsidian-markdown-formatting-assistant-plugin#48]
**Describe the bug**
Most of the interface elements are disabled.  Plugin does not seem to be working correctly. 
It expands the Text Edit section and closes the others, and the disclosure widget is missing.  
In particular, I cannot change the color of selected text.  
The plugin works in the "Help" vault but not in my daily use vault.  
I tried disabling other plugins and using the basic theme.  What can be interfering?  

**To Reproduce**
Install the plugin
Enable the plugin
Disable other community plugins.  
Use base theme.  

**Expected behavior**
I expected the interface to be as described in the README.  

**Screenshots**
![2022-04-26 10 03 53 CleanShot Obsidian](https://user-images.githubusercontent.com/4825448/165355445-5dd4a745-8c94-475b-9a9a-4658f9d7b70c.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser Safari
 - Obsidian Version 0.14.7

**Additional context**

**Comment by Reocin** [comment]
Hey @wealthychef1 

Yes and no. It is not really a bug, more a simplification for me as a programmer. It was quite hard to keep all the icons in a nice position with a flexible side pane. So i defined a min-width to keep the icons in the correct order (lines). This leads to this behavior you mentioned. Sorry for the quick fix here.

With the color. At the moment this is just a html styling helper, as in markdown there is no direct way to change the color. Just check the first and last checkbox below the save color button. Then a complete html tag should be inserted. 

At the moment, the Plugin does not work with the newest Obsidian Version, but i will fix this soon. Please follow the Issue https://github.com/Reocin/obsidian-markdown-formatting-assistant-plugin/issues/54

**Comment by wealthychef1** [comment]
Thank you!  Perhaps you can add an icon indicating that elements may be hidden to the left out of view if that is your conscious choice.  Totally understand your motivation and appreciate your work on making Obsidian a better tool.  I have been looking for a plugin which would allow me to just select some text and quickly color it using styles, HTML, whatever. To me that is the Holy Grail as yet missing in Obsidian: easily coloring text.  Perhaps it's for me to write that plug in someday...  :-). Cheers

**Comment by Reocin** [comment]
@wealthychef1 I already have some improvements of the coloring section in mind ;-)  I just need some time to code it. But this will take probably a couple of weeks or months as i'm soon in holiday. :-)

**Comment by wealthychef1** [comment]
Enjoy your time off!  Well deserved I'm sure.  If I get any chance, perhaps I can poke around in the code, but I also am traveling right now.

**Comment by Reocin** [comment]
Hey guys, it is just a quick fix, but the plugin should work again. **Please make sure that you use an obsidian version 0.15.x and update the plugin to the version 0.4.0**

Read also read the README for the new replacement of the trigger command `\`. It works now with the hotkey `ALT+Q` (it is just a quick update of the README. I will go through on another day)
