### ISSUE TITLE
Under the new version 0.15.6, it cannot work normally

### ISSUE THREAD

**Issue by wuzhen97** [Reocin/obsidian-markdown-formatting-assistant-plugin#53]
**Describe the bug**

Under the new version obsidian 0.15.6, it cannot work normally.

I guess it's caused by the focusing mode

**Screenshots**

https://user-images.githubusercontent.com/61906420/178894577-e2d3833a-64d0-49dc-a1ee-d6bf94e5bef6.mp4

**Comment by LFMM-33** [comment]
I agree, same behavior in my case and I have almost no modification in Obsidian (downloaded yesterday). The funny thing is yesterday it worked, today neither the side bar button nor the command line pops up.

**Comment by h2bx** [comment]
As a temporary workaround, you can spam press ESC while simultaneously pressing the buttons in the sidebar, this will allow the button to work just as focus is passed back to the actual note panel.

**Comment by wuzhen97** [comment]
> As a temporary workaround, you can spam press ESC while simultaneously pressing the buttons in the sidebar, this will allow the button to work just as focus is passed back to the actual note panel.

thank you，it works

**Comment by Reocin** [comment]
Hey guys, it is just a quick fix, but the plugin should work again. **Please make sure that you use an obsidian version 0.15.x and update the plugin to the version 0.4.0**

Read also read the README for the new replacement of the trigger command `\`. It works now with the hotkey `ALT+Q` (it is just a quick update of the README. I will go through on another day)
