### ISSUE TITLE
side panel can't expand

### ISSUE THREAD

**Issue by CGL5230** [Reocin/obsidian-markdown-formatting-assistant-plugin#56]
like my question, the side panel can not expand to choose the inside function(like"Text Edit"),but i still can use the hot key"alt+Q".
![image](https://user-images.githubusercontent.com/57136380/197140836-f849ad4d-5498-4cd7-b5ce-1abb6ba80799.png)

**Comment by Reocin** [comment]
Hey, thanks for your question. It is actually a common question and I will change the interface in the future. Sorry about that, but you have to make the side pane a bit wider until you see the arrows (see image below). Then just click one of them. If you click and hold on a title, you can change by drag and drop the order. Fore example, you could move the Latex section to the end if you don't need it often.

Please let me know if it solved your problem.


![image](https://user-images.githubusercontent.com/35258423/197142872-26bcf16b-43fa-405b-b077-ebd16b5568b3.png)

**Comment by CGL5230** [comment]
Thank you for your help. it's solved~
