### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Darakah** [Reocin/obsidian-markdown-formatting-assistant-plugin#8]
Many thanks for the great work!

**_1. Details Element:_**
- Used to create collapsible sections. Example can be found here https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab
I have it as a template currently but it would be nice to have it along the other elements, also might come in useful to other users.

**_2. Color Picker Improvements:_**

**_a. Block color addition when in preview mode_**: Currently when choosing a color it will be added to the cursor position even if preview mode is toggled (encountered this when was saving a set of commonly used colors)

**_b. Similar replacement behavior to the current elements:_** Currently when having a text selected and choosing an element it will be replace appropriately. This is very convenient and would be nice to have this same behavior for the color selection!

**_c. Keep tab in preferred color format:_** I know this one might not be possible or difficult just mentioning it, Hex is the easiest to use in my case and having to click three times every time when adding colors can be a bit annoying. As mentioned though the very nice option to save colors makes this request kinda meaningless :)

**_3. Element Responsive on Hover:_**
This is a suggest "nice" feel addition to the elements tab where when an element is hovered upon it would cause the element to seem to pop-out of the rest giving a nice feeling to it . This can be easily done with the following CSS. 

```
.html-element-box:hover {
    top: -2px;
    box-shadow: 0 4px 5px rgba(0, 0, 0, 0.2);
}
```

**Comment by Reocin** [comment]
Hey @Darakah 

Sorry that I'm so slowly. I'm still on it, but had some trouble at the table section. The commit will come soon :-)

**Comment by Reocin** [comment]
Hey @Darakah I added nearly all your request. Just update the plugin. But i wasn't able to fix the color picker to stay in the preferred color format. Sorry i tried all i know.

**Comment by Darakah** [comment]
@Reocin Thank you for the great work!!!

No worries about the color as the save option kinda solves as it is not used very often.
